import type {Metadata} from "next";
import "./global-styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import {Layout} from "@/components/layouts/layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body>
    <Layout>
      {children}
    </Layout>
    </body>
    </html>
  );
}
